repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: run.py
        args: [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
